name: Update image tag from dispatch
on:
  repository_dispatch:
    types: [update-image]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug received payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Image tag: ${{ github.event.client_payload.image_tag }}"

      - name: Update image tag in deployment.yaml
        run: |
          echo "Updating image tag to: ${{ github.event.client_payload.image_tag }}"
          sed -i "s|image: jazibumer/scd_proj_image:.*|image: jazibumer/scd_proj_image:${{ github.event.client_payload.image_tag }}|g" k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update image tag to ${{ github.event.client_payload.image_tag }}"
            git push
          fi
